In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!ls drive/MyDrive/ML/Praktikum1

Mounted at /content/drive
Automobile_data.csv  penjualanmobilNB.xlsx  tenis.xlsx
news_articles.csv    Peta.png

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
dataset = pd.read_excel("drive/MyDrive/ML/Praktikum1/tenis.xlsx")

In [ ]:
dataset

    No    Cuaca    suhu kelembaban berangin   main
0    1    cerah   panas     tinggi    salah  Tidak
1    2    cerah   panas     tinggi    benar  Tidak
2    3  berawan   panas     tinggi    salah     ya
3    4    hujan   sejuk     tinggi    salah     ya
4    5    hujan  dingin     Normal    salah     ya
5    6    hujan  dingin     Normal    benar     ya
6    7  berawan  dingin     Normal    benar     ya
7    8    cerah   sejuk     tinggi    salah  Tidak
8    9    cerah  dingin     Normal    salah     ya
9   10    hujan   sejuk     Normal    salah     ya
10  11    cerah   sejuk     Normal    benar     ya
11  12  berawan   sejuk     tinggi    benar     ya
12  13  berawan   panas     Normal    salah     ya
13  14    hujan   sejuk     tinggi    benar  Tidak

In [ ]:
x = dataset.iloc[:,:-1]

In [ ]:
x

    No    Cuaca    suhu kelembaban berangin
0    1    cerah   panas     tinggi    salah
1    2    cerah   panas     tinggi    benar
2    3  berawan   panas     tinggi    salah
3    4    hujan   sejuk     tinggi    salah
4    5    hujan  dingin     Normal    salah
5    6    hujan  dingin     Normal    benar
6    7  berawan  dingin     Normal    benar
7    8    cerah   sejuk     tinggi    salah
8    9    cerah  dingin     Normal    salah
9   10    hujan   sejuk     Normal    salah
10  11    cerah   sejuk     Normal    benar
11  12  berawan   sejuk     tinggi    benar
12  13  berawan   panas     Normal    salah
13  14    hujan   sejuk     tinggi    benar

In [ ]:
y=dataset.iloc[:,5]

In [ ]:
y

0     Tidak
1     Tidak
2        ya
3        ya
4        ya
5        ya
6        ya
7     Tidak
8        ya
9        ya
10       ya
11       ya
12       ya
13    Tidak
Name: main, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder_x = LabelEncoder()

In [ ]:
x = x.apply(LabelEncoder().fit_transform)

In [ ]:
x

    No  Cuaca  suhu  kelembaban  berangin
0    0      1     1           1         1
1    1      1     1           1         0
2    2      0     1           1         1
3    3      2     2           1         1
4    4      2     0           0         1
5    5      2     0           0         0
6    6      0     0           0         0
7    7      1     2           1         1
8    8      1     0           0         1
9    9      2     2           0         1
10  10      1     2           0         0
11  11      0     2           1         0
12  12      0     1           0         1
13  13      2     2           1         0

In [ ]:
from sklearn.tree import DecisionTreeClassifier
pd.get_dummies(dataset)

,No,Cuaca_berawan,Cuaca_cerah,Cuaca_hujan,suhu_dingin,suhu_panas,suhu_sejuk,kelembaban_Normal,kelembaban_tinggi,berangin_benar,berangin_salah,main_Tidak,main_ya
0,1,0,1,0,0,1,0,0,1,0,1,1,0
1,2,0,1,0,0,1,0,0,1,1,0,1,0
2,3,1,0,0,0,1,0,0,1,0,1,0,1
3,4,0,0,1,0,0,1,0,1,0,1,0,1
4,5,0,0,1,1,0,0,1,0,0,1,0,1
5,6,0,0,1,1,0,0,1,0,1,0,0,1
6,7,1,0,0,1,0,0,1,0,1,0,0,1
7,8,0,1,0,0,0,1,0,1,0,1,1,0
8,9,0,1,0,1,0,0,1,0,0,1,0,1
9,10,0,0,1,0,0,1,1,0,0,1,0,1
10,11,0,1,0,0,0,1,1,0,1,0,0,1
11,12,1,0,0,0,0,1,0,1,1,0,0,1
12,13,1,0,0,0,1,0,1,0,0,1,0,1
13,14,0,0,1,0,0,1,0,1,1,0,1,0

In [ ]:
regressor = DecisionTreeClassifier()

In [ ]:
X_in = np.array([1,1,1,1])

In [ ]:
regressor.fit(x.iloc[:, 1:5], y)

DecisionTreeClassifier()

In [ ]:
y_pred = regressor.predict([X_in])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [50]:
import six
import sys
sys.modules['sklearn.externals.six'] = six

In [54]:
from IPython.display import Image

In [55]:
from sklearn.tree import export_graphviz

In [56]:
import pydotplus

In [58]:
dot_data = pd.read_excel("drive/MyDrive/ML/Praktikum1/tenis.xlsx")

In [60]:
from io import StringIO

In [61]:
dot_data = StringIO()

In [63]:
export_graphviz(regressor, out_file = dot_data, filled= True, rounded= True, special_characters=True)

In [64]:
graph =pydotplus.graph_from_dot_data(dot_data.getvalue())

In [65]:
graph.write_png('tree.png')

True